const gfms = [
  {
    title: "HELP MY FAMILY STAY A LIVE",
    imageurl:
      "https://images.gofundme.com/gJGuIZ3eEEUCoZ4WKyQpi4wG0oc=/720x405/https://d2g8igdw686xgo.cloudfront.net/77500849_1704569910110074_r.jpeg",
    url: "https://www.gofundme.com/f/5xqws-gaza-relief",
  },
];

const apiRows = [
  {
    url: "https://www.gofundme.com/f/urgent-help-needed-reuniting-my-family-from-gaza?utm_campaign=p_cp+fundraiser-sidebar&utm_content=icons_with_impact_var_d&utm_medium=copy_link_all&utm_source=customer",
    progress: "$74,510",
  },
  {
    url: "https://www.gofundme.com/f/support-a-gazan-familys-basic-needs",
    progress: "$15,240",
  },
  {
    url: "https://www.gofundme.com/f/help-abdallah-get-from-gaza-to-australia?utm_campaign=p_cp+share-sheet&utm_medium=copy_link_all&utm_source=customer",
    progress: "$7,888",
  },
  {
    url: "https://www.papayoux-solidarite.com/fr/collecte/hope-for-gaza",
    progress: "$15,973",
  },
  {
    url: "https://www.gofundme.com/f/safe-passage-for-the-alkabariti-family-of-gaza?utm_campaign=unknown&utm_content=undefined&utm_medium=referral&utm_source=linktr.ee",
    progress: "$28,899",
  }
];

const spreadsheet = [
  {
    "Champion IG Handle": "",
    "GFM Link":
      "https://www.gofundme.com/f/help-osama-treat-his-son-and-rebuild-his-shattered-life",
    "Money Raised USD": "#N/A",
    "Target USD": "#N/A",
    "% Raised": "",
    "Quick Ref - who is it for?": "Osama - Nadia's friend",
    "IG Handle of GFM POC": "",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "04/06/2024",
    "Connected with Champion? Y/N": "FALSE",
    "Money Raised String": "#N/A",
    "Money Raised Value": "#N/A",
    Currency: "",
    "Target Raw": "",
    "Target base currency": "",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "FALSE",
  },
  {
    "Champion IG Handle": "",
    "GFM Link":
      "https://www.gofundme.com/f/hope-amidst-chaos-a-journey-to-rebuild-lives?utm_campaign=p_cp+fundraiser-sidebar&utm_medium=copy_link_all&utm_source=customer",
    "Money Raised USD": "$6,926",
    "Target USD": "n/a",
    "% Raised": "",
    "Quick Ref - who is it for?": "Ibrahim - Nadia's friend",
    "IG Handle of GFM POC": "",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "04/06/2024",
    "Connected with Champion? Y/N": "FALSE",
    "Money Raised String": "£5,558",
    "Money Raised Value": "5558",
    Currency: "GBP",
    "Target Raw": "",
    "Target base currency": "",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "FALSE",
  },
  {
    "Champion IG Handle": "",
    "GFM Link":
      "https://www.gofundme.com/f/help-dahlan-family-evacuate-to-safety?utm_campaign=p_lico+share-sheet&utm_medium=copy_link&utm_source=customer",
    "Money Raised USD": "$5,702",
    "Target USD": "",
    "% Raised": "",
    "Quick Ref - who is it for?":
      "Friend of Remie's Friend Hadeel Rizq-Qazzaz ",
    "IG Handle of GFM POC": "hadeelqazzaz",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "04/08/2024",
    "Connected with Champion? Y/N": "FALSE",
    "Money Raised String": "$7,885",
    "Money Raised Value": "7885",
    Currency: "CAD",
    "Target Raw": "",
    "Target base currency": "",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "FALSE",
  },
  {
    "Champion IG Handle": "",
    "GFM Link": "",
    "Money Raised USD": "#VALUE!",
    "Target USD": "",
    "% Raised": "",
    "Quick Ref - who is it for?":
      "Someone Rand knows -- she can connect us to the POC once we are ready",
    "IG Handle of GFM POC": "",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "04/08/2024",
    "Connected with Champion? Y/N": "FALSE",
    "Money Raised String": "#VALUE!",
    "Money Raised Value": "#VALUE!",
    Currency: "",
    "Target Raw": "",
    "Target base currency": "",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "FALSE",
  },
  {
    "Champion IG Handle": "",
    "GFM Link":
      "https://www.gofundme.com/f/help-tasneem-hazem-families-to-escape-from-death?utm_campaign=p_cp+share-sheet&utm_medium=copy_link_all&utm_source=customer&utm_term=CP_SSS_control",
    "Money Raised USD": "$1,208",
    "Target USD": "",
    "% Raised": "",
    "Quick Ref - who is it for?": "Sereen's Friend",
    "IG Handle of GFM POC": "Reach Sereen",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "04/08/2024",
    "Connected with Champion? Y/N": "FALSE",
    "Money Raised String": "$1,208",
    "Money Raised Value": "1208",
    Currency: "USD",
    "Target Raw": "",
    "Target base currency": "",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "FALSE",
  },
  {
    "Champion IG Handle": "",
    "GFM Link":
      "https://www.gofundme.com/f/help-reunite-a-cancer-hero-dad-with-family-in-gaza?utm_campaign=p_lico+share-sheet-first-launch&utm_medium=copy_link&utm_source=customer",
    "Money Raised USD": "$6,046",
    "Target USD": "",
    "% Raised": "",
    "Quick Ref - who is it for?": "Eman El Hayek husband",
    "IG Handle of GFM POC": "",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "04/12/2024",
    "Connected with Champion? Y/N": "FALSE",
    "Money Raised String": "€5,680",
    "Money Raised Value": "5680",
    Currency: "EUR",
    "Target Raw": "",
    "Target base currency": "",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "FALSE",
  },
  {
    "Champion IG Handle": "",
    "GFM Link":
      "https://www.gofundme.com/f/mt7jed-help-mahmoud-family-to-flee-from-gaza?utm_campaign=p_lico+share-sheet-first-launch&utm_medium=copy_link&utm_source=customer",
    "Money Raised USD": "$392",
    "Target USD": "",
    "% Raised": "",
    "Quick Ref - who is it for?": "Mafaz - friend of Aya Bseiso",
    "IG Handle of GFM POC": "mafaz_mushtaha",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "04/15/2024",
    "Connected with Champion? Y/N": "FALSE",
    "Money Raised String": "€368",
    "Money Raised Value": "368",
    Currency: "EUR",
    "Target Raw": "",
    "Target base currency": "",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "FALSE",
  },
  {
    "Champion IG Handle": "",
    "GFM Link":
      "https://www.gofundme.com/f/help-ahmad-and-her-family-to-survive-in-gaza",
    "Money Raised USD": "$4,430",
    "Target USD": "",
    "% Raised": "",
    "Quick Ref - who is it for?": "Ahmed Qadada - MC",
    "IG Handle of GFM POC": "Matt on WA",
    Contacted: "FALSE",
    "Opted in?": "FALSE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "FALSE",
    "Money Raised String": "£3,555",
    "Money Raised Value": "3555",
    Currency: "GBP",
    "Target Raw": "",
    "Target base currency": "",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "FALSE",
  },
  {
    "Champion IG Handle": "",
    "GFM Link":
      "https://www.gofundme.com/f/urgent-reliefevacuating-my-family-from-gazas-conflict-zone",
    "Money Raised USD": "$479",
    "Target USD": "",
    "% Raised": "",
    "Quick Ref - who is it for?": "Mohammed AlAnka - MC",
    "IG Handle of GFM POC": "Mohamed on WA",
    Contacted: "FALSE",
    "Opted in?": "FALSE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "FALSE",
    "Money Raised String": "€450",
    "Money Raised Value": "450",
    Currency: "EUR",
    "Target Raw": "",
    "Target base currency": "",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "FALSE",
  },
  {
    "Champion IG Handle": "",
    "GFM Link":
      "https://l.facebook.com/l.php?u=https%3A%2F%2Fgofund.me%2F914138a2%3Ffbclid%3DIwAR31iq4pSoSxOrxA-KWuqSpY3Tvy8LdGRRbNdMVS2GyD0vxRUQd4Gh257Io_aem_AWfbT-3fd7CxkZcL5SZE-r1dy0cxJf1h9ae86p8TF4A7Ij9-V-VrUq14XNN3PgCmkOVVU27vLEozg0yaWAIqxsGy&h=AT23U-YDId7d6cKQngscrnk35gdZCQnxX0QZZJ3vSU1wK0j18csrldyJ1G5UK8uw0xa4KhVQBS_jCTL5CsjS9TPOSw83ez44e57estaO-_96_GIkthrF9b8gYTM5QkrNkAtMvB3GdfrbJXrz_sPPYdRD",
    "Money Raised USD": "#N/A",
    "Target USD": "",
    "% Raised": "",
    "Quick Ref - who is it for?": "Ahmed Alami - FB matt",
    "IG Handle of GFM POC": "",
    Contacted: "FALSE",
    "Opted in?": "FALSE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "FALSE",
    "Money Raised String": "#N/A",
    "Money Raised Value": "#N/A",
    Currency: "",
    "Target Raw": "",
    "Target base currency": "",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "FALSE",
  },
  {
    "Champion IG Handle": "",
    "GFM Link":
      "https://www.gofundme.com/f/support-raghad-and-her-family-leave-from-gaza?utm_campaign=p_cp%2Bfundraiser-sidebar&utm_medium=copy_link_all&utm_source=customer",
    "Money Raised USD": "$77,023",
    "Target USD": "",
    "% Raised": "",
    "Quick Ref - who is it for?": "Sydney Apple connection",
    "IG Handle of GFM POC": "",
    Contacted: "FALSE",
    "Opted in?": "FALSE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "FALSE",
    "Money Raised String": "$77,023",
    "Money Raised Value": "77023",
    Currency: "USD",
    "Target Raw": "",
    "Target base currency": "",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "FALSE",
  },
  {
    "Champion IG Handle": "",
    "GFM Link":
      "https://www.gofundme.com/f/3yrfjr-rebuilding-the-dream?utm_campaign=p_cp+share-sheet&utm_medium=social&utm_source=instagram_story",
    "Money Raised USD": "$3,949",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "Reham Al Ghanima",
    "IG Handle of GFM POC": "",
    Contacted: "FALSE",
    "Opted in?": "FALSE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "FALSE",
    "Money Raised String": "$3,949",
    "Money Raised Value": "3949",
    Currency: "USD",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "FALSE",
    Notes: "I think we remove -- they need a GFM set up.",
    "Data Being Tracked": "FALSE",
  },
  {
    "Champion IG Handle": "",
    "GFM Link":
      "https://www.gofundme.com/f/inas-rezeq-evacuate-her-children-out-of-gaza",
    "Money Raised USD": "#N/A",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "Remie's friend ",
    "IG Handle of GFM POC": "",
    Contacted: "FALSE",
    "Opted in?": "FALSE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "FALSE",
    "Money Raised String": "#N/A",
    "Money Raised Value": "#N/A",
    Currency: "CAD",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "FALSE",
    Notes: "Remie to sort out",
    "Data Being Tracked": "FALSE",
  },
  {
    "Champion IG Handle": "@aditinramesh",
    "GFM Link":
      "https://www.gofundme.com/f/help-my-family-escape-the-crisis-in-gaza",
    "Money Raised USD": "",
    "Target USD": "",
    "% Raised": "",
    "Quick Ref - who is it for?": "Muath Khatib (Yosef Najjar's Friend)",
    "IG Handle of GFM POC": "muath.alkhatib",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "04/12/2024",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "",
    "Money Raised Value": "",
    Currency: "",
    "Target Raw": "",
    "Target base currency": "",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "FALSE",
  },
  {
    "Champion IG Handle": "@thekkumkattilmk",
    "GFM Link":
      "https://www.gofundme.com/f/from-war-to-hopehelp-move-my-family-to-safety?utm_campaign=p_cp+share-sheet&utm_medium=chat&utm_source=whatsApp",
    "Money Raised USD": "$4,220",
    "Target USD": "$0",
    "% Raised": "",
    "Quick Ref - who is it for?": "Mayar - GSG Community",
    "IG Handle of GFM POC": "Mayar h Abu Dalfa",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "04/06/2024",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "€3,965",
    "Money Raised Value": "3965",
    Currency: "EUR",
    "Target Raw": "",
    "Target base currency": "",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "FALSE",
  },
  {
    "Champion IG Handle": "kee.loo.eee",
    "GFM Link":
      "https://www.gofundme.com/f/help-our-family-to-escape-a-genocide?utm_campaign=p_cp+share-sheet&utm_content=control1&utm_medium=copy_link_all&utm_source=customer",
    "Money Raised USD": "$260",
    "Target USD": "",
    "% Raised": "",
    "Quick Ref - who is it for?": "Ahmed Nems - Nadia friend",
    "IG Handle of GFM POC": "ahmed_nems",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "04/05/2024",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "€260",
    "Money Raised Value": "260",
    Currency: "USD",
    "Target Raw": "",
    "Target base currency": "",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "FALSE",
  },
  {
    "Champion IG Handle": "@ashleybledsoe",
    "GFM Link":
      "https://www.gofundme.com/f/from-your-hearts-to-gaza-wafaa-family-nursery?attribution_id=sl:6479e85d-6b08-4f9c-9c01-96df3a19ad02&utm_campaign=p_cp+fundraiser-sidebar&utm_medium=copy_link_all&utm_source=customer",
    "Money Raised USD": "$1,798",
    "Target USD": "n/a",
    "% Raised": "",
    "Quick Ref - who is it for?": "Mai Temraz",
    "IG Handle of GFM POC": "@temrazmai",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "$2,805",
    "Money Raised Value": "2805",
    Currency: "AUD",
    "Target Raw": "",
    "Target base currency": "",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "FALSE",
  },
  {
    "Champion IG Handle": "@heyjudetanner",
    "GFM Link":
      "https://www.gofundme.com/f/rescuing-abeer-and-her-mom-from-war-in-gaza?attribution_id=sl:eefd6072-c980-468b-afc6-d6daff47a0bc&utm_campaign=p_cp+fundraiser-sidebar&utm_medium=copy_link_all&utm_source=customer",
    "Money Raised USD": "$13,493",
    "Target USD": "n/a",
    "% Raised": "",
    "Quick Ref - who is it for?": "Abeer (GSG community)",
    "IG Handle of GFM POC": "@abeeryounis913",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "$13,493",
    "Money Raised Value": "13493",
    Currency: "USD",
    "Target Raw": "",
    "Target base currency": "",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "FALSE",
  },
  {
    "Champion IG Handle": "@twancho",
    "GFM Link":
      "https://www.gofundme.com/f/sbfs6-help-me-and-my-family-escape-the-war-in-gaza?utm_campaign=p_lico+share-sheet-first-launch&utm_medium=copy_link&utm_source=customer",
    "Money Raised USD": "$958",
    "Target USD": "n/a",
    "% Raised": "",
    "Quick Ref - who is it for?":
      "Ebaa E Khoudary - Connection from Aya Bseiso",
    "IG Handle of GFM POC": "",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "$958",
    "Money Raised Value": "958",
    Currency: "USD",
    "Target Raw": "",
    "Target base currency": "",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "FALSE",
  },
  {
    "Champion IG Handle": "@mansurini",
    "GFM Link":
      "https://www.gofundme.com/f/help-hadeel-her-family-relocate-to-safety",
    "Money Raised USD": "$11,910",
    "Target USD": "n/a",
    "% Raised": "",
    "Quick Ref - who is it for?": "HadeelAl Maqadama (GSG community)",
    "IG Handle of GFM POC": "_hadeelr",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "€11,910",
    "Money Raised Value": "11910",
    Currency: "USD",
    "Target Raw": "",
    "Target base currency": "",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "FALSE",
  },
  {
    "Champion IG Handle": "@lkwitnicki",
    "GFM Link":
      "https://www.gofundme.com/f/help-my-family-escape-death-one-last-time?utm_campaign=p_cp+fundraiser-sidebar&utm_content=icons_only_var_c1&utm_medium=copy_link_all&utm_source=customer",
    "Money Raised USD": "$6,138",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "Ahmad Hamza",
    "IG Handle of GFM POC": "@ahmedhhamza",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "£4,926",
    "Money Raised Value": "4926",
    Currency: "GBP",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "FALSE",
  },
  {
    "Champion IG Handle": "Whitneymarble",
    "GFM Link":
      "https://www.gofundme.com/f/ahlna-fy-ghz-bhagh-mas-ldaamkm?utm_campaign=p_cp+share-sheet&utm_medium=copy_link_all&utm_source=customer&utm_term=undefined",
    "Money Raised USD": "$19,631",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "Alaa Elkhozondar",
    "IG Handle of GFM POC": "dr.alaa.elkhozondar",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "€18,444",
    "Money Raised Value": "18444",
    Currency: "EUR",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "FALSE",
    Notes: "Reached out on IG, seems legit",
    "Data Being Tracked": "FALSE",
  },
  {
    "Champion IG Handle": "@rakimwes ",
    "GFM Link":
      "https://www.gofundme.com/f/7vqhc-true-to-life?utm_medium=more&utm_source=customer&utm_campaign=p_cp%2Bshare-sheet&utm_term=undefined",
    "Money Raised USD": "#N/A",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "Nadia's friend zhour",
    "IG Handle of GFM POC": "zhour_m_s",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "€4,590",
    "Money Raised Value": "4590",
    Currency: "",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "FALSE",
  },
  {
    "Champion IG Handle": "@mehvs_",
    "GFM Link":
      "https://www.gofundme.com/f/bcm9d-rebuilding-dreams-a-medical-students-in-gaza-war?utm_campaign=p_lico+share-sheet-first-launch&utm_medium=copy_link&utm_source=customer",
    "Money Raised USD": "#N/A",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "Hashem Safi (Mortaga Brother in Law)",
    "IG Handle of GFM POC": "@hashem_safi125 ",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "€5,380",
    "Money Raised Value": "5380",
    Currency: "",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "TRUE",
  },
  {
    "Champion IG Handle": "@o_burt",
    "GFM Link":
      "https://www.gofundme.com/f/clinging-to-life-help-a-lovely-and-persistent-fam?utm_campaign=p_cp+fundraiser-sidebar&utm_medium=copy_link_all&utm_source=customer",
    "Money Raised USD": "$11,834",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "Remie's Friend Hadeel",
    "IG Handle of GFM POC": "hadeelqazzaz",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "$16,365",
    "Money Raised Value": "16365",
    Currency: "CAD",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "TRUE",
  },
  {
    "Champion IG Handle": "@rajvieee",
    "GFM Link":
      "https://www.gofundme.com/f/Urgent-humanitarian-appeal-to-save-my-family",
    "Money Raised USD": "$3,541",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "Aya Al Farra - GSG Community",
    "IG Handle of GFM POC": "aya_elfarra",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "$4,897",
    "Money Raised Value": "4897",
    Currency: "CAD",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "TRUE",
  },
  {
    "Champion IG Handle": "@dtdoods",
    "GFM Link":
      "https://www.gofundme.com/f/zbjhnp-please-help-my-family-escape-the-war-in-gaza?utm_campaign=p_cp+share-sheet&utm_medium=chat&utm_source=whatsApp&utm_term=undefined",
    "Money Raised USD": "$2,734",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "Lubna Al Farra Code Academy grad",
    "IG Handle of GFM POC": "@lubna_elfarra.web",
    Contacted: "TRUE",
    "Opted in?": "FALSE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "€2,569",
    "Money Raised Value": "2569",
    Currency: "EUR",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "TRUE",
    Notes: "",
    "Data Being Tracked": "TRUE",
  },
  {
    "Champion IG Handle": "@maggieinthesun",
    "GFM Link":
      "https://www.gofundme.com/f/help-hossam-abo-shab-to-evacuate-from-gaza?attribution_id=sl:dee3bec0-df6c-4d54-a165-13b9d8361a50&utm_campaign=p_cp+fundraiser-sidebar&utm_medium=chat&utm_source=whatsApp",
    "Money Raised USD": "$1,789",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "Ahmad Shatat - Yalla, G4",
    "IG Handle of GFM POC": "",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "kr19,547",
    "Money Raised Value": "19547",
    Currency: "SEK",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "TRUE",
    Notes: "",
    "Data Being Tracked": "TRUE",
  },
  {
    "Champion IG Handle": "@khajeewhajee",
    "GFM Link":
      "https://www.gofundme.com/f/war-torn-dreams-help-gaza-engineer-family-rebuild?sharetype=teams&member=33196709&utm_medium=social&utm_source=instagram&utm_campaign=p_na+share-sheet",
    "Money Raised USD": "$1,864",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "Mohsen",
    "IG Handle of GFM POC": "mohsen_afana",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "€1,751",
    "Money Raised Value": "1751",
    Currency: "EUR",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "TRUE",
  },
  {
    "Champion IG Handle": "@leylatonak",
    "GFM Link":
      "https://www.gofundme.com/f/urgent-support-to-help-us-escape-gaza?utm_campaign=p_cp+share-sheet&utm_content=control1&utm_medium=copy_link_all&utm_source=customer",
    "Money Raised USD": "$838",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "Ahmed Shaheen",
    "IG Handle of GFM POC": "",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "£838",
    "Money Raised Value": "838",
    Currency: "USD",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "FALSE",
    Notes: "Need IG handle",
    "Data Being Tracked": "TRUE",
  },
  {
    "Champion IG Handle": "@luovery",
    "GFM Link":
      "https://www.gofundme.com/f/help-ahmed-shatats-family-escape-wartorn-gaza",
    "Money Raised USD": "$1,171",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "Ahmad Shatat, G4, tall one",
    "IG Handle of GFM POC":
      "https://www.instagram.com/ahmadmshatat?igsh=bWJqaW43OHN2M3Bj&utm_source=qr",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "€1,100",
    "Money Raised Value": "1100",
    Currency: "EUR",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "TRUE",
    Notes: "",
    "Data Being Tracked": "TRUE",
  },
  {
    "Champion IG Handle": "@kbtuckett",
    "GFM Link":
      "https://www.gofundme.com/f/help-evacuate-jamals-family-from-gaza?utm_campaign=p_lico+share-sheet-first-launch&utm_medium=copy_link&utm_source=customer",
    "Money Raised USD": "#N/A",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "Jamal",
    "IG Handle of GFM POC": "",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "#N/A",
    "Money Raised Value": "#N/A",
    Currency: "USD",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "TRUE",
  },
  {
    "Champion IG Handle": "@butteratroomtemp",
    "GFM Link":
      "https://www.gofundme.com/f/dq6sg-help-ahmeds-family-get-out-of-the-gaza-strip?utm_campaign=p_cp+fundraiser-sidebar&utm_medium=copy_link_all&utm_source=customer",
    "Money Raised USD": "$1,854",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "Friend of khwaiter (Ahmed Timraz)",
    "IG Handle of GFM POC": "",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "$1,742",
    "Money Raised Value": "1742",
    Currency: "EUR",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "TRUE",
    Notes: "",
    "Data Being Tracked": "TRUE",
  },
  {
    "Champion IG Handle": "@claire.valdivia",
    "GFM Link":
      "https://www.gofundme.com/f/75xcc-donate-to-help-us-build-a-warm-and-safe-home?utm_campaign=p_cp+fundraiser-sidebar&utm_medium=chat&utm_source=whatsApp",
    "Money Raised USD": "$17,270",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "Hadi, brother of Shahenaz Friend",
    "IG Handle of GFM POC": "@hadi_soboh",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "€16,226",
    "Money Raised Value": "16226",
    Currency: "EUR",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "TRUE",
  },
  {
    "Champion IG Handle": "@y3ll0wRose",
    "GFM Link":
      "https://www.gofundme.com/f/pap7g-help-a-family-from-gaza-to-have-a-secure-life?utm_campaign=p_cp%2Bfundraiser-sidebar&utm_medium=copy_link_all&utm_source=customer",
    "Money Raised USD": "$8,771",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?":
      "Bara'a Khalil - from IG, happens to be Sara Afifi's cousin",
    "IG Handle of GFM POC": "_baraakhalil",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "€8,241",
    "Money Raised Value": "8241",
    Currency: "EUR",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "TRUE",
  },
  {
    "Champion IG Handle": "@fakerayka",
    "GFM Link":
      "https://www.gofundme.com/f/helping-hayas-family?utm_campaign=p_cp+share-sheet&utm_content=control1&utm_medium=copy_link_all&utm_source=customer",
    "Money Raised USD": "$2,886",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "Asala Kamal - GSG CA",
    "IG Handle of GFM POC": "",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "£2,316",
    "Money Raised Value": "2316",
    Currency: "GBP",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "TRUE",
  },
  {
    "Champion IG Handle": "@sarahallibhoy",
    "GFM Link":
      "https://www.gofundme.com/f/urgent-appeal-save-innocent-lives-in-gazahelp-br?utm_campaign=p_cp+share-sheet&utm_medium=copy_link_all&utm_source=customer",
    "Money Raised USD": "$12,195",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "Sereen's family",
    "IG Handle of GFM POC": "",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "€11,458",
    "Money Raised Value": "11458",
    Currency: "EUR",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "TRUE",
    Notes: "",
    "Data Being Tracked": "TRUE",
  },
  {
    "Champion IG Handle": "@janejay.tanner",
    "GFM Link":
      "https://www.gofundme.com/f/help-a-single-mother-and-her-son-get-to-safety?utm_campaign=p_cp+share-sheet&utm_content=control1&utm_medium=copy_link_all&utm_source=customer",
    "Money Raised USD": "$11,975",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "Eman El Hayek, GSG staff",
    "IG Handle of GFM POC": "",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "€11,251",
    "Money Raised Value": "11251",
    Currency: "EUR",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "TRUE",
    Notes: "",
    "Data Being Tracked": "TRUE",
  },
  {
    "Champion IG Handle": "@whatradicalizedyou ",
    "GFM Link": "https://www.gofundme.com/f/r5gau-help-a-family-in-gaza",
    "Money Raised USD": "$3,988",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "Fatma Siam",
    "IG Handle of GFM POC": "",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "€3,747",
    "Money Raised Value": "3747",
    Currency: "EUR",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "TRUE",
  },
  {
    "Champion IG Handle": "Jem",
    "GFM Link":
      "https://www.gofundme.com/f/nbxx53-help-adham-and-his-family-escape-the-war-in-gaza?utm_campaign=p_lico+share-sheet&utm_medium=copy_link&utm_source=customer",
    "Money Raised USD": "$10,422",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "Adham Code Academy",
    "IG Handle of GFM POC": "",
    Contacted: "TRUE",
    "Opted in?": "FALSE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "£8,364",
    "Money Raised Value": "8364",
    Currency: "GBP",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "FALSE",
    Notes: "Jem Championing already",
    "Data Being Tracked": "TRUE",
  },
  {
    "Champion IG Handle": "@ansari.notsorry ",
    "GFM Link":
      "https://www.gofundme.com/f/help-abdullah-and-his-family-seek-refuge-from-gaza?utm_campaign=p_lico+share-sheet-first-launch&utm_medium=copy_link&utm_source=customer",
    "Money Raised USD": "$12,930",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "Abdallah Mezied",
    "IG Handle of GFM POC": "@its.abood01",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "£10,377",
    "Money Raised Value": "10377",
    Currency: "GBP",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "TRUE",
  },
  {
    "Champion IG Handle": "@gmwiegold",
    "GFM Link":
      "https://www.gofundme.com/f/emans-story-healing-hearts-and-rebuilding-dreams?utm_campaign=p_lico+share-sheet-first-launch&utm_medium=copy_link&utm_source=customer",
    "Money Raised USD": "$6,819",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "Samar Fayez (CA Grad)",
    "IG Handle of GFM POC": "",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "€6,407",
    "Money Raised Value": "6407",
    Currency: "EUR",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "TRUE",
  },
  {
    "Champion IG Handle": "@patty_paine",
    "GFM Link":
      "https://www.gofundme.com/f/help-basmah-and-her-family-escape-the-war?utm_campaign=p_lico+share-sheet&utm_medium=copy_link&utm_source=customer",
    "Money Raised USD": "$19,669",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "Basmaa",
    "IG Handle of GFM POC": "@basmah.shaladan",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "€18,480",
    "Money Raised Value": "18480",
    Currency: "EUR",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "TRUE",
  },
  {
    "Champion IG Handle": "c__elaina",
    "GFM Link":
      "https://www.gofundme.com/f/r85nb-help-nadas-son-and-siblings-get-out-of-gaza?utm_campaign=p_cp%2Bfundraiser-sidebar&utm_medium=copy_link_all&utm_source=customer",
    "Money Raised USD": "$11,042",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "Noour Hammad's sister",
    "IG Handle of GFM POC": "",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "€10,374",
    "Money Raised Value": "10374",
    Currency: "EUR",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "TRUE",
  },
  {
    "Champion IG Handle": "@brooklynstani",
    "GFM Link":
      "https://www.gofundme.com/f/ymshk-urgent-appeal-help-evacuate-my-family-from-gaza?utm_campaign=p_cp+share-sheet&utm_medium=copy_link_all&utm_source=customer",
    "Money Raised USD": "$20,529",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "Nizar",
    "IG Handle of GFM POC": "",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "CHF18,742",
    "Money Raised Value": "18742",
    Currency: "CHF",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "TRUE",
    Notes: "",
    "Data Being Tracked": "TRUE",
  },
  {
    "Champion IG Handle": "@chessieneedham",
    "GFM Link":
      "https://www.gofundme.com/f/evacuations-from-gaza?utm_campaign=p_lico+share-sheet&utm_medium=copy_link&utm_source=customer",
    "Money Raised USD": "#N/A",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "Ayah - GSG community",
    "IG Handle of GFM POC": "",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "#N/A",
    "Money Raised Value": "#N/A",
    Currency: "EUR",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "TRUE",
  },
  {
    "Champion IG Handle": "@asap_baba",
    "GFM Link":
      "https://www.gofundme.com/f/urnat-help-my-family-escape-gaza?member=32831937&sharetype=teams&utm_campaign=p_na+share-sheet&utm_medium=copy_link&utm_source=customer",
    "Money Raised USD": "$7,775",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "Mohannad G5",
    "IG Handle of GFM POC": "",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "$7,775",
    "Money Raised Value": "7775",
    Currency: "USD",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "FALSE",
    Notes: "OUT",
    "Data Being Tracked": "TRUE",
  },
  {
    "Champion IG Handle": "joe",
    "GFM Link": "https://www.gofundme.com/f/hope-for-baby-farah-and-family",
    "Money Raised USD": "$11,095",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "Mohamed Alfarra - NO SM right now",
    "IG Handle of GFM POC": "",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "$11,095",
    "Money Raised Value": "11095",
    Currency: "USD",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "FALSE",
    Notes: "Connected him with my friend Joe",
    "Data Being Tracked": "TRUE",
  },
  {
    "Champion IG Handle": "Vern",
    "GFM Link":
      "https://www.gofundme.com/f/emergency-please-help-rebuild-danial-family-lives",
    "Money Raised USD": "$19,020",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "Wissam",
    "IG Handle of GFM POC": "",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "$19,020",
    "Money Raised Value": "19020",
    Currency: "USD",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "TRUE",
  },
  {
    "Champion IG Handle": "@amaaanndda",
    "GFM Link": "https://www.gofundme.com/f/help-souhib-flee-gazas-war",
    "Money Raised USD": "$9,975",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "Motassem Awaja",
    "IG Handle of GFM POC": "",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "kr109,003",
    "Money Raised Value": "109003",
    Currency: "SEK",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "TRUE",
    Notes: "",
    "Data Being Tracked": "TRUE",
  },
  {
    "Champion IG Handle": "@radicalbirding ",
    "GFM Link":
      "https://www.gofundme.com/f/292aa-support-our-familys-escape-from-genocide?utm_campaign=p_lico+share-sheet-first-launch&utm_medium=copy_link&utm_source=customer",
    "Money Raised USD": "$17,575",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "Wa'ad",
    "IG Handle of GFM POC":
      "https://www.instagram.com/waadsoboh?igsh=MzRlODBiNWFlZA==",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "€16,512",
    "Money Raised Value": "16512",
    Currency: "EUR",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "TRUE",
  },
  {
    "Champion IG Handle": "@sloanyboney24",
    "GFM Link":
      "https://www.gofundme.com/f/help-save-elmadhoun-family-from-gaza-genocide?utm_campaign=p_cp+share-sheet&utm_medium=copy_link_all&utm_source=customer",
    "Money Raised USD": "$15,995",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "Da7boul",
    "IG Handle of GFM POC": "",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "$15,995",
    "Money Raised Value": "15995",
    Currency: "USD",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "TRUE",
  },
  {
    "Champion IG Handle": "@c_cauterucci",
    "GFM Link":
      "https://www.gofundme.com/f/help-my-family-find-safety-away-from-gaza",
    "Money Raised USD": "$12,820",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "Shahenaz",
    "IG Handle of GFM POC": "",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "€12,045",
    "Money Raised Value": "12045",
    Currency: "EUR",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "FALSE",
    Notes: "OUT",
    "Data Being Tracked": "TRUE",
  },
  {
    "Champion IG Handle": "@kamzill",
    "GFM Link":
      "https://www.gofundme.com/f/help-mohammed-and-yara-rebuild-their-home-in-gaza",
    "Money Raised USD": "$15,171",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "Mohammed Mortaja",
    "IG Handle of GFM POC": "",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "€14,254",
    "Money Raised Value": "14254",
    Currency: "EUR",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "TRUE",
  },
  {
    "Champion IG Handle": "@rscottmunro",
    "GFM Link":
      "https://www.gofundme.com/f/aya-mhmd-new-beg-in-gaza?utm_medium=copy_link_all&utm_source=customer&utm_campaign=p_cp%2Bfundraiser-sidebar&utm_content=icons_with_impact_var_d",
    "Money Raised USD": "$22,059",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "Aya & Mohammed",
    "IG Handle of GFM POC": "",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "€20,725",
    "Money Raised Value": "20725",
    Currency: "EUR",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "TRUE",
  },
  {
    "Champion IG Handle": "@leylatonak",
    "GFM Link":
      "https://www.gofundme.com/f/urgent-appeal-to-save-sami-and-his-mother-from-the",
    "Money Raised USD": "$11,913",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "Sami, Code Acadamy",
    "IG Handle of GFM POC": "",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "€11,193",
    "Money Raised Value": "11193",
    Currency: "EUR",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "TRUE",
  },
  {
    "Champion IG Handle": "@savannahenglish",
    "GFM Link":
      "https://www.gofundme.com/f/emergency-evacuation-of-grandparents-in-gaza?utm_campaign=unknown&utm_content=undefined&utm_medium=referral&utm_source=linktr.ee",
    "Money Raised USD": "$13,921",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "Ismail Grandparents",
    "IG Handle of GFM POC": "",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "$19,250",
    "Money Raised Value": "19250",
    Currency: "CAD",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "FALSE",
    Notes: "OUT",
    "Data Being Tracked": "TRUE",
  },
  {
    "Champion IG Handle": "erimurr",
    "GFM Link":
      "https://www.gofundme.com/f/urgent-plea-evacuate-family-amidst-gaza-genocide",
    "Money Raised USD": "$18,413",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "Saleh AbuShamala's family",
    "IG Handle of GFM POC": "",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "£14,777",
    "Money Raised Value": "14777",
    Currency: "GBP",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "TRUE",
    Notes:
      "Need to put in IG group, saleh doesn't follow matt so can't receive messages yet",
    "Data Being Tracked": "TRUE",
  },
  {
    "Champion IG Handle": "@whatradicalizedyou",
    "GFM Link":
      "https://www.gofundme.com/f/path-to-safety-assisting-a-gazan-family",
    "Money Raised USD": "$22,029",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "Muhammed Qumboz & his wife's fundraiser too",
    "IG Handle of GFM POC": "",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "$22,029",
    "Money Raised Value": "22029",
    Currency: "USD",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "TRUE",
  },
  {
    "Champion IG Handle": "@thornfieldfarmer",
    "GFM Link":
      "https://www.gofundme.com/f/emergency-help-me-reunite-and-evacuate-my-family?utm_campaign=p_cp+share-sheet&utm_medium=copy_link_all&utm_source=customer",
    "Money Raised USD": "$18,215",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "Yosef al Najjar's Family",
    "IG Handle of GFM POC": "",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "£14,618",
    "Money Raised Value": "14618",
    Currency: "GBP",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "TRUE",
  },
  {
    "Champion IG Handle": "@chermosa",
    "GFM Link":
      "https://www.gofundme.com/f/help-samahs-family-to-get-out-of-gaza?member=32801575&utm_campaign=p_lico+share-sheet&utm_medium=copy_link&utm_source=customer",
    "Money Raised USD": "$32,246",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "Samah Ramadan",
    "IG Handle of GFM POC": "",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "€30,296",
    "Money Raised Value": "30296",
    Currency: "EUR",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "TRUE",
  },
  {
    "Champion IG Handle": "@freethemall11",
    "GFM Link":
      "https://www.gofundme.com/f/help-us-save-our-families-from-gazas-genocide",
    "Money Raised USD": "$20,071",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "Israa Alsaafin and Fedaa Nassar",
    "IG Handle of GFM POC": "@mahmoud.ziad.nassar",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "$20,071",
    "Money Raised Value": "20071",
    Currency: "USD",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "TRUE",
    Notes: "",
    "Data Being Tracked": "TRUE",
  },
  {
    "Champion IG Handle": "Complete",
    "GFM Link":
      "https://www.gofundme.com/f/urgent-relief-for-palestinian-family?utm_campaign=unknown&utm_content=undefined&utm_medium=referral&utm_source=linktr.ee",
    "Money Raised USD": "$19,801",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?":
      "Abdallah Sheikh Ali -- HE IS OUT OF GAZA NOW",
    "IG Handle of GFM POC": "",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "$19,801",
    "Money Raised Value": "19801",
    Currency: "USD",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "FALSE",
    Notes: "OUT",
    "Data Being Tracked": "FALSE",
  },
  {
    "Champion IG Handle": "@laurenmariko",
    "GFM Link": "https://gogetfunding.com/a-desperate-appeal-from-gaza/",
    "Money Raised USD": "$23,331",
    "Target USD": "$33,000",
    "% Raised": "71%",
    "Quick Ref - who is it for?": "Anas Shami - former GSG staff",
    "IG Handle of GFM POC":
      "https://www.instagram.com/ahmadmshatat?igsh=bWJqaW43OHN2M3Bj&utm_source=qr",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "US$23,331",
    "Money Raised Value": "23331",
    Currency: "USD",
    "Target Raw": "",
    "Target base currency": "33000",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "TRUE",
  },
  {
    "Champion IG Handle": "@howboutdemapplez",
    "GFM Link":
      "https://www.gofundme.com/f/a-beacon-of-hope-for-the-alsafadi-family-in-gaza?utm_campaign=p_lico+share-sheet-first-launch&utm_medium=copy_link&utm_source=customer",
    "Money Raised USD": "$30,518",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "AlSafadi Family",
    "IG Handle of GFM POC": "@qamar_safadi",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "£24,492",
    "Money Raised Value": "24492",
    Currency: "GBP",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "TRUE",
  },
  {
    "Champion IG Handle": "@chrisyisuh",
    "GFM Link":
      "https://www.gofundme.com/f/urgent-rescue-mission-for-the-mortaja-family?utm_campaign=p_cp+fundraiser-sidebar&utm_medium=copy_link_all&utm_source=customer",
    "Money Raised USD": "$38,081",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "Hani's family",
    "IG Handle of GFM POC": "",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "€35,778",
    "Money Raised Value": "35778",
    Currency: "EUR",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "TRUE",
  },
  {
    "Champion IG Handle": "@saracmatheson",
    "GFM Link": "https://www.gofundme.com/f/ghandour-family-gaza",
    "Money Raised USD": "$30,619",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "Doaa Ghandour",
    "IG Handle of GFM POC": "",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "$30,619",
    "Money Raised Value": "30619",
    Currency: "USD",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "TRUE",
  },
  {
    "Champion IG Handle": "@mehreeniqbal87",
    "GFM Link":
      "https://www.gofundme.com/f/ytsg95-please-help-me-the-baby-who-will-be-born?utm_campaign=p_cp+share-sheet&utm_medium=copy_link_all&utm_source=customer",
    "Money Raised USD": "$35,826",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?":
      "Mahmoud & Hussein's Friend - asked Mahmoud for intro",
    "IG Handle of GFM POC": "",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "€33,660",
    "Money Raised Value": "33660",
    Currency: "EUR",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "TRUE",
  },
  {
    "Champion IG Handle": "@jennifer.laming",
    "GFM Link":
      "https://www.gofundme.com/f/give-our-families-in-gaza-the-gift-of-relief?utm_campaign=unknown&utm_content=undefined&utm_medium=referral&utm_source=linktr.ee",
    "Money Raised USD": "$39,546",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "Salam Daloul",
    "IG Handle of GFM POC": "",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "€37,155",
    "Money Raised Value": "37155",
    Currency: "EUR",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "TRUE",
  },
  {
    "Champion IG Handle": "Complete",
    "GFM Link":
      "https://www.gofundme.com/f/v77vfk-help-my-family-escape-war-in-gaza?utm_campaign=p_cp+share-sheet&utm_medium=copy_link_all&utm_source=customer",
    "Money Raised USD": "#N/A",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "Ibrahim Hameed - gofundme closed for now?",
    "IG Handle of GFM POC": "",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "FALSE",
    "Money Raised String": "#N/A",
    "Money Raised Value": "#N/A",
    Currency: "USD",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "FALSE",
    Notes: "CLOSED",
    "Data Being Tracked": "FALSE",
  },
  {
    "Champion IG Handle": "Amrit",
    "GFM Link":
      "https://www.gofundme.com/f/help-nadia-and-her-family-out-of-gaza?utm_campaign=p_cp+fundraiser-sidebar&utm_medium=copy_link_all&utm_source=customer",
    "Money Raised USD": "$46,033",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "Nadia",
    "IG Handle of GFM POC": "",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "$46,033",
    "Money Raised Value": "46033",
    Currency: "USD",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "FALSE",
    Notes: "OUT",
    "Data Being Tracked": "FALSE",
  },
  {
    "Champion IG Handle": "@thingsarecool321",
    "GFM Link":
      "https://www.gofundme.com/f/help-support-my-friend-in-gza?utm_campaign=p_cp+share-sheet&utm_content=control1&utm_medium=copy_link_all&utm_source=customer",
    "Money Raised USD": "$50,675",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "Ahmed Issa",
    "IG Handle of GFM POC": "@ahmedissahq",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "£40,668",
    "Money Raised Value": "40668",
    Currency: "GBP",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "TRUE",
  },
  {
    "Champion IG Handle": "@pfarm",
    "GFM Link":
      "https://www.gofundme.com/f/saedhabibfamily?utm_campaign=p_cp+share-sheet&utm_content=control1&utm_medium=copy_link_all&utm_source=customer",
    "Money Raised USD": "$82,444",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "Saed",
    "IG Handle of GFM POC": "",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "€77,459",
    "Money Raised Value": "77459",
    Currency: "EUR",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "TRUE",
  },
  {
    "Champion IG Handle": "@mishajapanwala",
    "GFM Link":
      "https://www.gofundme.com/f/urgent-help-needed-reuniting-my-family-from-gaza?utm_campaign=p_cp+fundraiser-sidebar&utm_content=icons_with_impact_var_d&utm_medium=copy_link_all&utm_source=customer",
    "Money Raised USD": "$74,510",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "Sara Alafifi",
    "IG Handle of GFM POC": "",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "€70,004",
    "Money Raised Value": "70004",
    Currency: "EUR",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "TRUE",
  },
  {
    "Champion IG Handle": "@jenny_greenteeth",
    "GFM Link":
      "https://www.gofundme.com/f/support-a-gazan-familys-basic-needs",
    "Money Raised USD": "$15,240",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "Angham - GSG Code Academy",
    "IG Handle of GFM POC": "",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "£12,231",
    "Money Raised Value": "12231",
    Currency: "GBP",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "TRUE",
  },
  {
    "Champion IG Handle": "@carolinahidalgomccabe",
    "GFM Link":
      "https://www.gofundme.com/f/help-abdallah-get-from-gaza-to-australia?utm_campaign=p_cp+share-sheet&utm_medium=copy_link_all&utm_source=customer",
    "Money Raised USD": "$7,888",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "Abdallah Aljazzar, former GSG staff",
    "IG Handle of GFM POC": "",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "$12,306",
    "Money Raised Value": "12306",
    Currency: "AUD",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "TRUE",
  },
  {
    "Champion IG Handle": "@cass_cass_do ",
    "GFM Link": "https://www.papayoux-solidarite.com/fr/collecte/hope-for-gaza",
    "Money Raised USD": "$15,973",
    "Target USD": "$26,609",
    "% Raised": "60%",
    "Quick Ref - who is it for?": "Abeer",
    "IG Handle of GFM POC": "",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "15 007,66 €",
    "Money Raised Value": "15007",
    Currency: "EUR",
    "Target Raw": "",
    "Target base currency": "25000",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "TRUE",
  },
  {
    "Champion IG Handle": "@amanithepoet",
    "GFM Link":
      "https://www.gofundme.com/f/help-omar-and-his-family-get-through-the-hardships?utm_campaign=p_cp+share-sheet&utm_medium=copy_link_all&utm_source=customer",
    "Money Raised USD": "#N/A",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "Mahmoud Khwaiter Bro",
    "IG Handle of GFM POC": "",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "#N/A",
    "Money Raised Value": "#N/A",
    Currency: "USD",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "TRUE",
  },
  {
    "Champion IG Handle": "@jmegzz",
    "GFM Link":
      "https://www.gofundme.com/f/safe-passage-for-the-alkabariti-family-of-gaza?utm_campaign=unknown&utm_content=undefined&utm_medium=referral&utm_source=linktr.ee",
    "Money Raised USD": "$28,899",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "Sabrin Alkabariti",
    "IG Handle of GFM POC": "",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "£23,192",
    "Money Raised Value": "23192",
    Currency: "GBP",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "TRUE",
  },
  {
    "Champion IG Handle": "@gtbluelilly",
    "GFM Link": "https://www.gofundme.com/f/5xqws-gaza-relief",
    "Money Raised USD": "#N/A",
    "Target USD": "#N/A",
    "% Raised": "#N/A",
    "Quick Ref - who is it for?": "Friend of Shahenaz",
    "IG Handle of GFM POC": "@hebaaburamadan93",
    Contacted: "TRUE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "$5,129",
    "Money Raised Value": "5129",
    Currency: "",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "FALSE",
    Notes: "",
    "Data Being Tracked": "FALSE",
  },
  {
    "Champion IG Handle": "@spencerthespacecadet ",
    "GFM Link": "",
    "Money Raised USD": "#VALUE!",
    "Target USD": "#N/A",
    "% Raised": "#VALUE!",
    "Quick Ref - who is it for?": "Qamar's friend (set up outside of us)",
    "IG Handle of GFM POC": "",
    Contacted: "FALSE",
    "Opted in?": "TRUE",
    "Opt In Date": "",
    "Connected with Champion? Y/N": "TRUE",
    "Money Raised String": "#VALUE!",
    "Money Raised Value": "#VALUE!",
    Currency: "",
    "Target Raw": "",
    "Target base currency": "#N/A",
    "Needs Support": "FALSE",
    Notes: "Friend of @howboutdemapplez",
    "Data Being Tracked": "FALSE",
  },
];

const tableRows = [
  [
    "https://www.gofundme.com/f/help-osama-treat-his-son-and-rebuild-his-shattered-life",
    "https://d2g8igdw686xgo.cloudfront.net/79350445_1712425592797163_r.jpeg",
    "Donate to Help Osama treat his son and rebuild his shattered life, organized by Ibrahim Hasan",
  ],
  [
    "https://www.gofundme.com/f/hope-amidst-chaos-a-journey-to-rebuild-lives?utm_campaign=p_cp+fundraiser-sidebar&utm_medium=copy_link_all&utm_source=customer",
    "https://d2g8igdw686xgo.cloudfront.net/77593341_1705674195635123_r.jpeg",
    "Donate to Hope Amidst Chaos: Gaza's Journey to Rebuild Lives, organized by Ibrahim Hasan",
  ],
  [
    "https://www.gofundme.com/f/help-dahlan-family-evacuate-to-safety?utm_campaign=p_lico+share-sheet&utm_medium=copy_link&utm_source=customer",
    "https://d2g8igdw686xgo.cloudfront.net/79358645_171245501312616_r.jpeg",
    "Donate to Help Dahlan Family Evacuate to Safety (Border Fees), organized by Wad Taweel",
  ],
  [
    "https://www.gofundme.com/f/help-tasneem-hazem-families-to-escape-from-death?utm_campaign=p_cp+share-sheet&utm_medium=copy_link_all&utm_source=customer&utm_term=CP_SSS_control",
    "https://d2g8igdw686xgo.cloudfront.net/78145441_170998071241804_r.jpeg",
    "Donate to Help Families of Tasneem & Hazem Escape from Death, organized by Omar Musallam",
  ],
  [
    "https://www.gofundme.com/f/help-reunite-a-cancer-hero-dad-with-family-in-gaza?utm_campaign=p_lico+share-sheet-first-launch&utm_medium=copy_link&utm_source=customer",
    "https://d2g8igdw686xgo.cloudfront.net/78749003_1709801879338709_r.jpeg",
    "Donate to Help reunite cancer hero dad with family from Gaza, organized by Mohammad Mansour",
  ],
  [
    "https://www.gofundme.com/f/mt7jed-help-mahmoud-family-to-flee-from-gaza?utm_campaign=p_lico+share-sheet-first-launch&utm_medium=copy_link&utm_source=customer",
    "https://d2g8igdw686xgo.cloudfront.net/79137877_1711655950917629_r.jpeg",
    "Donate to Urgent: Help shaymaa and her family flee the war, organized by alaa alhayek",
  ],
  [
    "https://www.gofundme.com/f/help-ahmad-and-her-family-to-survive-in-gaza",
    "https://d2g8igdw686xgo.cloudfront.net/79485515_1713015040843623_r.jpeg",
    "Donate to Help Ahmed and his family get out of Gaza, organized by Mhmd Al-Ghanem",
  ],
  [
    "https://www.gofundme.com/f/urgent-reliefevacuating-my-family-from-gazas-conflict-zone",
    "https://d2g8igdw686xgo.cloudfront.net/79353891_17130328322684_r.jpeg",
    "Donate to Urgent Relief:Evacuating My Family from Gaza's Conflict Zone, organized by Mohammed Ahmed",
  ],
  [
    "https://www.gofundme.com/f/save-the-lives-of-the-elalmi-family-in-gaza?utm_campaign=p_cp+share-sheet&utm_medium=copy_link_all&utm_source=customer",
    "https://d2g8igdw686xgo.cloudfront.net/79395221_1712673829128314_r.jpeg",
    "Donate to Save the Lives of my Student's Family in Gaza, organized by Edwin Morrill",
  ],
  [
    "https://www.gofundme.com/f/support-raghad-and-her-family-leave-from-gaza?utm_campaign=p_cp%2Bfundraiser-sidebar&utm_medium=copy_link_all&utm_source=customer",
    "https://d2g8igdw686xgo.cloudfront.net/77112947_170253262564832_r.jpeg",
    "Donate to Support Raghad and her family leave from Gaza, organized by Noor Zanaid",
  ],
  [
    "https://www.gofundme.com/f/3yrfjr-rebuilding-the-dream?utm_campaign=p_cp+share-sheet&utm_medium=social&utm_source=instagram_story",
    "https://d2g8igdw686xgo.cloudfront.net/77666489_1705400820226537_r.jpeg",
    "Donate to Help me Evacuate my Family from Gaza, organized by Reeham ghanima",
  ],
  [
    "https://www.gofundme.com/f/inas-rezeq-evacuate-her-children-out-of-gaza",
    "https://d2g8igdw686xgo.cloudfront.net/78696707_1709657931388552_r.jpeg",
    "Donate to Help Enas Rezeq evacuate her children out of Gaza, organized by Saeb Qazzaz",
  ],
  [
    "https://www.gofundme.com/f/help-my-family-escape-the-crisis-in-gaza",
    "https://d2g8igdw686xgo.cloudfront.net/77836703_1707501846355410_r.png",
    "Donate to Help my Family escape the Crisis in Gaza, organized by Khalil Alkhatib",
  ],
  [
    "https://www.gofundme.com/f/from-war-to-hopehelp-move-my-family-to-safety?utm_campaign=p_cp+share-sheet&utm_medium=chat&utm_source=whatsApp",
    "https://d2g8igdw686xgo.cloudfront.net/78496015_1712428113363810_r.jpeg",
    "Donate to From War to Hope: Move Mayar's Family to Safety, organized by Yara ElMaghrabi",
  ],
  [
    "https://www.gofundme.com/f/help-our-family-to-escape-a-genocide?utm_campaign=p_cp+share-sheet&utm_content=control1&utm_medium=copy_link_all&utm_source=customer",
    "https://d2g8igdw686xgo.cloudfront.net/78497323_1708773533315445_r.jpeg",
    "Donate to Help our Family to Escape a Genocide, organized by Ahmed Nems",
  ],
  [
    "https://www.gofundme.com/f/from-your-hearts-to-gaza-wafaa-family-nursery?attribution_id=sl%3A6479e85d-6b08-4f9c-9c01-96df3a19ad02&utm_campaign=p_cp+fundraiser-sidebar&utm_medium=copy_link_all&utm_source=customer",
    "https://d2g8igdw686xgo.cloudfront.net/79063617_1711145259303434_r.png",
    "Donate to From your hearts to Gaza, Wafa's family & Nursery!, organized by Lama Al Ramahi",
  ],
  [
    "https://www.gofundme.com/f/rescuing-abeer-and-her-mom-from-war-in-gaza?attribution_id=sl%3Aeefd6072-c980-468b-afc6-d6daff47a0bc&utm_campaign=p_cp+fundraiser-sidebar&utm_medium=copy_link_all&utm_source=customer",
    "https://d2g8igdw686xgo.cloudfront.net/78913035_1710515925354669_r.jpeg",
    "Donate to Rescue Abeer and Her Mom from War in Gaza, organized by Jessica Dickinson Goodman",
  ],
  [
    "https://www.gofundme.com/f/sbfs6-help-me-and-my-family-escape-the-war-in-gaza?utm_campaign=p_lico+share-sheet-first-launch&utm_medium=copy_link&utm_source=customer",
    "https://d2g8igdw686xgo.cloudfront.net/79121489_1711477149211591_r.jpeg",
    "Donate to Help me and my family escape the war in Gaza, organized by Ebaa Ayman",
  ],
  [
    "https://www.gofundme.com/f/help-hadeel-her-family-relocate-to-safety",
    "https://d2g8igdw686xgo.cloudfront.net/79087365_1711265087163846_r.jpeg",
    "Donate to Help Hadeel & her family relocate to safety, organized by Leah Ní Ghríofa",
  ],
  [
    "https://www.gofundme.com/f/help-my-family-escape-death-one-last-time?utm_campaign=p_cp+fundraiser-sidebar&utm_content=icons_only_var_c1&utm_medium=copy_link_all&utm_source=customer",
    "https://d2g8igdw686xgo.cloudfront.net/77517399_1707294470802140_r.jpeg",
    "Donate to Help my Family Escape Death One Last Time, organized by Ahmed Hamza",
  ],
  [
    "https://www.gofundme.com/f/ahlna-fy-ghz-bhagh-mas-ldaamkm?utm_campaign=p_cp+share-sheet&utm_medium=copy_link_all&utm_source=customer&utm_term=undefined",
    "https://d2g8igdw686xgo.cloudfront.net/78351701_1709118933497937_r.jpeg",
    "Donate to HELP ME EVACUATE MY FAMILY OUT OF GAZA WAR, organized by Mustafa Alkhazendar",
  ],
  [
    "https://www.gofundme.com/f/7vqhc-true-to-life?utm_medium=more&utm_source=customer&utm_campaign=p_cp%2Bshare-sheet&utm_term=undefined",
    "https://d2g8igdw686xgo.cloudfront.net/79223399_1712955784640851_r.jpg",
    "Donate to My right to life as a human being, organized by Nabil EL Sabagh",
  ],
  [
    "https://www.gofundme.com/f/bcm9d-rebuilding-dreams-a-medical-students-in-gaza-war?utm_campaign=p_lico+share-sheet-first-launch&utm_medium=copy_link&utm_source=customer",
    "https://d2g8igdw686xgo.cloudfront.net/78729625_1709805565118923_r.jpeg",
    "Donate to Rebuilding Dreams: A Medical Student's in Gaza War, organized by hashem safi",
  ],
  [
    "https://www.gofundme.com/f/clinging-to-life-help-a-lovely-and-persistent-fam?utm_campaign=p_cp+fundraiser-sidebar&utm_medium=copy_link_all&utm_source=customer",
    "https://d2g8igdw686xgo.cloudfront.net/78775665_1709919120479668_r.png",
    "Donate to Clinging to Life: Help a Lovely and Persistent Fam, organized by Mohammad Qazzaz",
  ],
  [
    "https://www.gofundme.com/f/Urgent-humanitarian-appeal-to-save-my-family",
    "https://d2g8igdw686xgo.cloudfront.net/77831227_1710508055980607_r.png",
    "Donate to Help my family of 10 to evacuate from Gaza, organised by Aya Alfarra",
  ],
  [
    "https://www.gofundme.com/f/zbjhnp-please-help-my-family-escape-the-war-in-gaza?utm_campaign=p_cp+share-sheet&utm_medium=chat&utm_source=whatsApp&utm_term=undefined",
    "https://d2g8igdw686xgo.cloudfront.net/78888095_1710427146895042_r.jpeg",
    "Donate to Please Help my Family to Survive from Gaza War!, organized by Nada Al-farra",
  ],
  [
    "https://www.gofundme.com/f/help-hossam-abo-shab-to-evacuate-from-gaza?attribution_id=sl%3Adee3bec0-df6c-4d54-a165-13b9d8361a50&utm_campaign=p_cp+fundraiser-sidebar&utm_medium=chat&utm_source=whatsApp",
    "https://d2g8igdw686xgo.cloudfront.net/78737435_1709756468504099_r.png",
    "Donate to Help Hossam evacuate & Finish his studies., organized by Haydi Kayyal",
  ],
  [
    "https://www.gofundme.com/f/war-torn-dreams-help-gaza-engineer-family-rebuild?sharetype=teams&member=33196709&utm_medium=social&utm_source=instagram&utm_campaign=p_na+share-sheet",
    "https://d2g8igdw686xgo.cloudfront.net/78990895_1710862876796365_r.jpeg",
    "Donate to War Torn Dreams: Help Gaza Engineer Family Rebuild, organized by Katherine Young",
  ],
  [
    "https://www.gofundme.com/f/urgent-support-to-help-us-escape-gaza?utm_campaign=p_cp+share-sheet&utm_content=control1&utm_medium=copy_link_all&utm_source=customer",
    "https://d2g8igdw686xgo.cloudfront.net/78477051_1708689619886533_r.jpeg",
    "Donate to help us to evacuate from Gaza, organized by Hisham Shahin",
  ],
  [
    "https://www.gofundme.com/f/help-ahmed-shatats-family-escape-wartorn-gaza",
    "https://d2g8igdw686xgo.cloudfront.net/78663281_170967773427435_r.jpeg",
    "Donate to Stand with Us: Supporting Family Affected by Gaza, organized by Abdallah Shatat",
  ],
  [
    "https://www.gofundme.com/f/help-evacuate-jamals-family-from-gaza?utm_campaign=p_lico+share-sheet-first-launch&utm_medium=copy_link&utm_source=customer",
    "https://d2g8igdw686xgo.cloudfront.net/79100261_1711322945962932_r.jpeg",
    "Donate to Help Evacuate Jamal's Family from Gaza, organized by Katherine Tuckett",
  ],
  [
    "https://www.gofundme.com/f/dq6sg-help-ahmeds-family-get-out-of-the-gaza-strip?utm_campaign=p_cp+fundraiser-sidebar&utm_medium=copy_link_all&utm_source=customer",
    "https://d2g8igdw686xgo.cloudfront.net/78749931_1709809495488145_r.jpeg",
    "Donate to Help Ahmed's family get out of Gaza Strip, organized by Ahmed Timraz",
  ],
  [
    "https://www.gofundme.com/f/75xcc-donate-to-help-us-build-a-warm-and-safe-home?utm_campaign=p_cp+fundraiser-sidebar&utm_medium=chat&utm_source=whatsApp",
    "https://d2g8igdw686xgo.cloudfront.net/78382129_1710684506326611_r.jpeg",
    "Donate to Help To Escape From Gaza ., organized by Hadi Soboh",
  ],
  [
    "https://www.gofundme.com/f/pap7g-help-a-family-from-gaza-to-have-a-secure-life?utm_campaign=p_cp%2Bfundraiser-sidebar&utm_medium=copy_link_all&utm_source=customer",
    "https://d2g8igdw686xgo.cloudfront.net/78997857_1711154680652733_r.jpeg",
    "Donate to Help A Family From Gaza To Have A secure Life, organized by Mohammed abu Harb",
  ],
  [
    "https://www.gofundme.com/f/helping-hayas-family?utm_campaign=p_cp+share-sheet&utm_content=control1&utm_medium=copy_link_all&utm_source=customer",
    "https://d2g8igdw686xgo.cloudfront.net/78593741_1709231534814522_r.jpeg",
    "Donate to Help Baby Hayat and her Family to evacuate Gaza, organized by Asala Matarya",
  ],
  [
    "https://www.gofundme.com/f/urgent-appeal-save-innocent-lives-in-gazahelp-br?utm_campaign=p_cp+share-sheet&utm_medium=copy_link_all&utm_source=customer",
    "https://d2g8igdw686xgo.cloudfront.net/77415147_1711465216482814_r.jpeg",
    "Donate to Urgent Appeal- Gaza: Help evacuate my family., organized by Karem Al-Kahlout",
  ],
  [
    "https://www.gofundme.com/f/help-a-single-mother-and-her-son-get-to-safety?utm_campaign=p_cp+share-sheet&utm_content=control1&utm_medium=copy_link_all&utm_source=customer",
    "https://d2g8igdw686xgo.cloudfront.net/78646935_1709397320876666_r.png",
    "Donate to Help a single mother and her son get to safety!!!, organized by Ada Hukelic",
  ],
  [
    "https://www.gofundme.com/f/r5gau-help-a-family-in-gaza",
    "https://d2g8igdw686xgo.cloudfront.net/78433843_1710252916107234_r.jpg",
    "Donate to Support Mohammed and  his family, organized by Hani Alnajjar",
  ],
  [
    "https://www.gofundme.com/f/nbxx53-help-adham-and-his-family-escape-the-war-in-gaza?utm_campaign=p_lico+share-sheet&utm_medium=copy_link&utm_source=customer",
    "https://d2g8igdw686xgo.cloudfront.net/78845729_1710333556676505_r.jpeg",
    "Donate to Help Adham and his family escape the Gaza war, organized by Jem Abulhawa",
  ],
  [
    "https://www.gofundme.com/f/help-abdullah-and-his-family-seek-refuge-from-gaza?utm_campaign=p_lico+share-sheet-first-launch&utm_medium=copy_link&utm_source=customer",
    "https://d2g8igdw686xgo.cloudfront.net/78114983_1707224021466915_r.jpeg",
    "Donate to Help Abdullah and His Family Seek Refuge From Gaza, organized by Nadine Jibeili",
  ],
  [
    "https://www.gofundme.com/f/emans-story-healing-hearts-and-rebuilding-dreams?utm_campaign=p_lico+share-sheet-first-launch&utm_medium=copy_link&utm_source=customer",
    "https://d2g8igdw686xgo.cloudfront.net/78666501_1712260232212890_r.jpeg",
    "Donate to Eman from Gaza: Healing and Rebuilding Dreams, organized by Husain Aljazzar",
  ],
  [
    "https://www.gofundme.com/f/help-basmah-and-her-family-escape-the-war?utm_campaign=p_lico+share-sheet&utm_medium=copy_link&utm_source=customer",
    "https://d2g8igdw686xgo.cloudfront.net/78714323_1712078466753899_r.jpeg",
    "Donate to Urgent: Help Basmah and her family flee the war, organized by Mutasem Daher",
  ],
  [
    "https://www.gofundme.com/f/r85nb-help-nadas-son-and-siblings-get-out-of-gaza?utm_campaign=p_cp%2Bfundraiser-sidebar&utm_medium=copy_link_all&utm_source=customer",
    "https://d2g8igdw686xgo.cloudfront.net/78308329_1708031564566026_r.jpeg",
    "Donate to Help Nada’s son and siblings get out of Gaza, organized by Reem Saed",
  ],
  [
    "https://www.gofundme.com/f/ymshk-urgent-appeal-help-evacuate-my-family-from-gaza?utm_campaign=p_cp+share-sheet&utm_medium=copy_link_all&utm_source=customer",
    "https://d2g8igdw686xgo.cloudfront.net/77406001_1709911327751483_r.jpeg",
    "Fai una donazione a Urgent Appeal: Help Evacuate My Family from Gaza, organizzata da Nezar Zakout",
  ],
  [
    "https://www.gofundme.com/f/evacuations-from-gaza?utm_campaign=p_lico+share-sheet&utm_medium=copy_link&utm_source=customer",
    "https://d2g8igdw686xgo.cloudfront.net/78091815_1709477631839660_r.jpeg",
    "Donate to Ayah's Appeal: Rebuilding Life Beyond the Horrors, organized by Katherine Young",
  ],
  [
    "https://www.gofundme.com/f/urnat-help-my-family-escape-gaza?member=32831937&sharetype=teams&utm_campaign=p_na+share-sheet&utm_medium=copy_link&utm_source=customer",
    "https://d2g8igdw686xgo.cloudfront.net/78663107_1709453050949295_r.jpg",
    "Donate to Help my family escape Gaza., organized by Yousef  Hanafi",
  ],
  [
    "https://www.gofundme.com/f/hope-for-baby-farah-and-family",
    "https://d2g8igdw686xgo.cloudfront.net/78615731_1709243550130531_r.jpeg",
    "Donate to Hope for Baby Farah and Family, organized by Hala Ibrahim",
  ],
  [
    "https://www.gofundme.com/f/emergency-please-help-rebuild-danial-family-lives",
    "https://d2g8igdw686xgo.cloudfront.net/78148947_1707344483799505_r.jpeg",
    "Donate to Help Daniel & Eilea have childhood they deserve, organized by Mahmoud Al-Madhoun",
  ],
  [
    "https://www.gofundme.com/f/help-souhib-flee-gazas-war",
    "https://d2g8igdw686xgo.cloudfront.net/77346899_1708511920443704_r.png",
    "Donate to Help Souhib Flee Gaza's War, organized by Motassem Awaja",
  ],
  [
    "https://www.gofundme.com/f/292aa-support-our-familys-escape-from-genocide?utm_campaign=p_lico+share-sheet-first-launch&utm_medium=copy_link&utm_source=customer",
    "https://d2g8igdw686xgo.cloudfront.net/78651741_1709454033832181_r.jpeg",
    "Donate to Support Our Family's Escape from Genocide., organized by Alaa Shaheen",
  ],
  [
    "https://www.gofundme.com/f/help-save-elmadhoun-family-from-gaza-genocide?utm_campaign=p_cp+share-sheet&utm_medium=copy_link_all&utm_source=customer",
    "https://d2g8igdw686xgo.cloudfront.net/78243609_1708390137607171_r.jpeg",
    "Donate to Help save  Almadhoun family from Gaza genocide., organized by Ahmed Abuzaid",
  ],
  [
    "https://www.gofundme.com/f/help-my-family-find-safety-away-from-gaza",
    "https://d2g8igdw686xgo.cloudfront.net/78347157_1710184629729104_r.jpeg",
    "Donate to Help My Family Find Safety Away from Gaza, organized by Shahenaz Monia",
  ],
  [
    "https://www.gofundme.com/f/help-mohammed-and-yara-rebuild-their-home-in-gaza",
    "https://d2g8igdw686xgo.cloudfront.net/77773995_1706128420484838_r.jpeg",
    "Donate to Help Mohammed & Yara Rebuild Their Life in Gaza, organized by Mohammed Mortaga",
  ],
  [
    "https://www.gofundme.com/f/aya-mhmd-new-beg-in-gaza?utm_medium=copy_link_all&utm_source=customer&utm_campaign=p_cp%2Bfundraiser-sidebar&utm_content=icons_with_impact_var_d",
    "https://d2g8igdw686xgo.cloudfront.net/77690661_1710189533401921_r.png",
    "Donate to Emergency: help us rescue ourselves and our family, organized by Ayah Jomaa",
  ],
  [
    "https://www.gofundme.com/f/urgent-appeal-to-save-sami-and-his-mother-from-the",
    "https://d2g8igdw686xgo.cloudfront.net/77755253_1705698972252936_r.jpeg",
    "Donate to Save Sami & His Mother from the Brink of Genocide, organized by Aseel Muqbel",
  ],
  [
    "https://www.gofundme.com/f/emergency-evacuation-of-grandparents-in-gaza?utm_campaign=unknown&utm_content=undefined&utm_medium=referral&utm_source=linktr.ee",
    "https://d2g8igdw686xgo.cloudfront.net/77841317_1706281600799007_r.jpeg",
    "Donate to Emergency evacuation of grandparents in Gaza, organized by Laila Masri",
  ],
  [
    "https://www.gofundme.com/f/urgent-plea-evacuate-family-amidst-gaza-war",
    "https://d2g8igdw686xgo.cloudfront.net/78160723_1710881597647790_r.jpeg",
    "Spende für Urgent Plea: Evacuate Family Amidst Gaza War, organisiert von Saleh AbuShamala",
  ],
  [
    "https://www.gofundme.com/f/path-to-safety-assisting-a-gazan-family",
    "https://d2g8igdw686xgo.cloudfront.net/77380081_1703974900723003_r.jpeg",
    "Donate to Path to Safety: Assisting a Gazan Family, organized by Muhammad Qumboz",
  ],
  [
    "https://www.gofundme.com/f/emergency-help-me-reunite-and-evacuate-my-family?utm_campaign=p_cp+share-sheet&utm_medium=copy_link_all&utm_source=customer",
    "https://d2g8igdw686xgo.cloudfront.net/78303199_1708091334498355_r.png",
    "Donate to Urgent: Help Me Evacuate My Family From Gaza, organized by Yousef Alnajjar",
  ],
  [
    "https://www.gofundme.com/f/help-samahs-family-to-get-out-of-gaza?member=32801575&utm_campaign=p_lico+share-sheet&utm_medium=copy_link&utm_source=customer",
    "https://d2g8igdw686xgo.cloudfront.net/78632371_1709316724322475_r.jpeg",
    "Donate to HELP Samah’s family to get out of Gaza, organized by Ayah Sayed Bakry Mahmoud",
  ],
  [
    "https://www.gofundme.com/f/help-us-save-our-families-from-gazas-genocide",
    "https://d2g8igdw686xgo.cloudfront.net/78330369_1708222327601122_r.jpeg",
    "Donate to Our plea to help our families leave Gaza, organized by Israa Alsaafin",
  ],
  [
    "https://www.gofundme.com/f/urgent-relief-for-palestinian-family?utm_campaign=unknown&utm_content=undefined&utm_medium=referral&utm_source=linktr.ee",
    "https://d2g8igdw686xgo.cloudfront.net/77443677_1704358053958080_r.jpeg",
    "Donate to Urgent Relief for Palestinian Family, organized by Stephanie Normantas",
  ],
  [
    "https://gogetfunding.com/a-desperate-appeal-from-gaza/",
    "https://assets.gogetfunding.com/wp-content/uploads/2024/01/8371268/img/cimg_8371268_1705340912.jpeg",
    "Help Anas and his family evacuate Gaza!",
  ],
  [
    "https://www.gofundme.com/f/a-beacon-of-hope-for-the-alsafadi-family-in-gaza?utm_campaign=p_lico+share-sheet-first-launch&utm_medium=copy_link&utm_source=customer",
    "https://d2g8igdw686xgo.cloudfront.net/77389329_170410597889_r.jpeg",
    "Donate to A Beacon of hope for the AlSafadi Family in Gaza, organized by SAHAR R H  ALSAFADI",
  ],
  [
    "https://www.gofundme.com/f/urgent-rescue-mission-for-the-mortaja-family?utm_campaign=p_cp+fundraiser-sidebar&utm_medium=copy_link_all&utm_source=customer",
    "https://d2g8igdw686xgo.cloudfront.net/78645733_1709760410733832_r.png",
    "Donate to Urgent Rescue Mission for the Mortaja Family, organized by Hani Mortaja",
  ],
  [
    "https://www.gofundme.com/f/ghandour-family-gaza",
    "https://d2g8igdw686xgo.cloudfront.net/77975239_1706648236442745_r.png",
    "Donate to Ghandour Family Gaza Fundraiser, organized by Palestine Skating Game",
  ],
  [
    "https://www.gofundme.com/f/ytsg95-please-help-me-the-baby-who-will-be-born?utm_campaign=p_cp+share-sheet&utm_medium=copy_link_all&utm_source=customer",
    "https://d2g8igdw686xgo.cloudfront.net/77832931_1706192560765837_r.jpeg",
    "Donate to help the baby who will be born get out of Genocide, organized by Samar Ais",
  ],
  [
    "https://www.gofundme.com/f/give-our-families-in-gaza-the-gift-of-relief?utm_campaign=unknown&utm_content=undefined&utm_medium=referral&utm_source=linktr.ee",
    "https://d2g8igdw686xgo.cloudfront.net/77457537_1704382407529669_r.png",
    "Donate to Give our Families in Gaza the Gift of Relief, organized by Salam Dalloul",
  ],
  [
    "https://www.gofundme.com/f/v77vfk-help-my-family-escape-war-in-gaza?utm_campaign=p_cp+share-sheet&utm_medium=copy_link_all&utm_source=customer",
    "https://d2g8igdw686xgo.cloudfront.net/77938005_1706482111432467_r.jpeg",
    "Donate to Help My Family Escape War in Gaza, organized by Yoseph ح",
  ],
  [
    "https://www.gofundme.com/f/help-nadia-and-her-family-out-of-gaza?utm_campaign=p_cp+fundraiser-sidebar&utm_medium=copy_link_all&utm_source=customer",
    "https://d2g8igdw686xgo.cloudfront.net/78236153_1707848689794924_r.jpeg",
    "Donate to Help get Nadia Abu Shaban & her family out of Gaza, organized by Ahmad Akel",
  ],
  [
    "https://www.gofundme.com/f/help-support-my-friend-in-gza?utm_campaign=p_cp+share-sheet&utm_content=control1&utm_medium=copy_link_all&utm_source=customer",
    "https://d2g8igdw686xgo.cloudfront.net/78171171_1708354529366416_r.jpeg",
    "Donate to Help Ahmed's family survive Gaza War, organized by Ahmed Issa",
  ],
  [
    "https://www.gofundme.com/f/saedhabibfamily?utm_campaign=p_cp+share-sheet&utm_content=control1&utm_medium=copy_link_all&utm_source=customer",
    "https://d2g8igdw686xgo.cloudfront.net/78519745_170888090060050_r.jpeg",
    "Donate to Help Saed Habib Get His Family Out of Gaza, organized by Holly Elissa Dignard",
  ],
  [
    "https://www.gofundme.com/f/urgent-help-needed-reuniting-my-family-from-gaza?utm_campaign=p_cp+fundraiser-sidebar&utm_content=icons_with_impact_var_d&utm_medium=copy_link_all&utm_source=customer",
    "https://d2g8igdw686xgo.cloudfront.net/78113295_1707212367652268_r.jpeg",
    "Donate to Urgent Help Needed: Reuniting My Family from Gaza, organized by Sara Alafifi",
  ],
  [
    "https://www.gofundme.com/f/support-a-gazan-familys-basic-needs",
    "https://d2g8igdw686xgo.cloudfront.net/78441379_1708557617752943_r.jpeg",
    "Donate to Bring hope to Lulu and her family in G4z4, organized by Dina Venes",
  ],
  [
    "https://www.gofundme.com/f/help-abdallah-get-out-of-gaza",
    "https://d2g8igdw686xgo.cloudfront.net/78213719_1707644050570805_r.jpeg",
    "Donate to Help get Abdallah out of Gaza, organized by Jesse Boylan",
  ],
  [
    "https://www.papayoux-solidarite.com/fr/collecte/hope-for-gaza",
    "https://www.papayoux-solidarite.com/asso/photos/img_65dc77f59140c.jpg",
    "Campagne de dons : De la guerre à la paix : aider ma famille à évacuer Gaza ",
  ],
  [
    "https://www.gofundme.com/f/help-omar-and-his-family-get-through-the-hardships?utm_campaign=p_cp+share-sheet&utm_medium=copy_link_all&utm_source=customer",
    "https://d2g8igdw686xgo.cloudfront.net/77373915_1708771522901401_r.jpg",
    "Donate to Support getting Omar and his family out of Gaza, organized by Dina Azouz",
  ],
  [
    "https://www.gofundme.com/f/safe-passage-for-the-alkabariti-family-of-gaza?utm_campaign=unknown&utm_content=undefined&utm_medium=referral&utm_source=linktr.ee",
    "https://d2g8igdw686xgo.cloudfront.net/77388607_1711741724305548_r.jpeg",
    "Donate to Help save the Alkabariti family of Gaza, organized by Yousef Tuqan",
  ],
  [
    "https://www.gofundme.com/f/5xqws-gaza-relief",
    "https://d2g8igdw686xgo.cloudfront.net/77500849_1704569910110074_r.jpeg",
    "Donate to HELP MY FAMILY STAY A LIVE, organized by Mohammed Samhouri",
  ],
];

module.exports = {
  gfms,
  apiRows,
  spreadsheet,
  tableRows,
};
